version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: mongo-autogestao
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongo_data:/data/db
    networks:
      - autogestao-net

  minio:
    image: minio/minio:latest
    container_name: minio-autogestao
    restart: unless-stopped
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    networks:
      - autogestao-net

volumes:
  mongo_data:
  minio_data:

networks:
  autogestao-net: